#!/usr/bin/env bash
#
# Generates homebrew formulas for all tools based on the artifacts of a
# published GitHub release. Downloads the release tar.gz files, computes
# the sha256 checksums and renders the formula files into dist/.
#
# Usage: ./scripts/gen-formula.sh <version> [output-dir]
#
# Requires the gh CLI (authenticated) and an existing GitHub release
# with all native artifacts attached (created by the release workflow).
#
# See readme/release.md for the full process description.
#
set -euo pipefail

VERSION="${1:?Usage: gen-formula.sh <version> [output-dir]}"
OUT_DIR="${2:-dist}"

# keep in sync with the tool modules
TOOLS=(jregex)

REPO="mhus/mhus-jknife"
TAG="v$VERSION"

command -v gh >/dev/null || { echo "ERROR: gh CLI not found (https://cli.github.com/)" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "ERROR: gh is not authenticated (run: gh auth login)" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "### Downloading release assets of $TAG"
gh release download "$TAG" --repo "$REPO" --dir "$WORK" --clobber

sha_of() {
    local tool="$1" rid="$2"
    local file="$WORK/$tool-$VERSION-$rid.tar.gz"
    if [[ ! -f "$file" ]]; then
        echo "ERROR: release asset missing: $tool-$VERSION-$rid.tar.gz" >&2
        exit 1
    fi
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$file" | awk '{print $1}'
    else
        sha256sum "$file" | awk '{print $1}'
    fi
}

desc_of() {
    case "$1" in
    jregex) echo "Java regex helper tool (match, find, replace)" ;;
    *) echo "mhus-jknife tool $1" ;;
    esac
}

# jregex -> Jregex, jfoo-bar -> JfooBar
class_name() {
    printf '%s' "$1" | tr -d '-' | awk '{print toupper(substr($0,1,1)) substr($0,2)}'
}

mkdir -p "$OUT_DIR"
for TOOL in "${TOOLS[@]}"; do
    CLASS="$(class_name "$TOOL")"
    OUT_FILE="$OUT_DIR/$TOOL.rb"

    cat >"$OUT_FILE" <<EOF
# Generated by scripts/gen-formula.sh for $TAG -- do not edit manually.
class $CLASS < Formula
  desc "$(desc_of "$TOOL")"
  homepage "https://github.com/$REPO"
  version "$VERSION"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/$REPO/releases/download/$TAG/$TOOL-$VERSION-macos-x86_64.tar.gz"
      sha256 "$(sha_of "$TOOL" macos-x86_64)"
    else
      url "https://github.com/$REPO/releases/download/$TAG/$TOOL-$VERSION-macos-aarch64.tar.gz"
      sha256 "$(sha_of "$TOOL" macos-aarch64)"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/$REPO/releases/download/$TAG/$TOOL-$VERSION-linux-x86_64.tar.gz"
      sha256 "$(sha_of "$TOOL" linux-x86_64)"
    else
      url "https://github.com/$REPO/releases/download/$TAG/$TOOL-$VERSION-linux-aarch64.tar.gz"
      sha256 "$(sha_of "$TOOL" linux-aarch64)"
    end
  end

  def install
    bin.install "$TOOL"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/$TOOL --version")
  end
end
EOF

    echo "### Formula written: $OUT_FILE"
done

echo ""
echo "### Next steps:"
echo "    1. copy the formula(s) into the tap repo: cp $OUT_DIR/*.rb <tap>/Formula/"
echo "    2. commit & push the tap"
echo "    3. verify: brew tap $REPO_HOMEBREW && brew install $TOOL && $TOOL --version"
