# Homebrew formula template
#
# This is a human-readable reference for the formula layout.
# The real formulas for a release are GENERATED by scripts/gen-formula.sh
# (with correct urls and sha256 checksums) — do not maintain them by hand.

class Jregex < Formula
  desc "Java regex helper tool (match, find, replace)"
  homepage "https://github.com/mhus/mhus-jknife"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/mhus-jknife/releases/download/v#{version}/jregex-#{version}-macos-x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/mhus/mhus-jknife/releases/download/v#{version}/jregex-#{version}-macos-aarch64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhus/mhus-jknife/releases/download/v#{version}/jregex-#{version}-linux-x86_64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/mhus/mhus-jknife/releases/download/v#{version}/jregex-#{version}-linux-aarch64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "jregex"
  end

  test do
    assert_equal "true", shell_output("#{bin}/jregex match '^a+c$' aaac").strip
    assert_equal "12\n345", shell_output("#{bin}/jregex find '\\d+' 'a 12 b 345 c'").strip
  end
end
